# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Iamlive < Formula
  desc "Generate an IAM policy from AWS calls using client-side monitoring (CSM) or embedded proxy."
  homepage "https://github.com/iann0036/iamlive"
  version "0.22.0"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/iann0036/iamlive/releases/download/v0.22.0/iamlive-v0.22.0-darwin-amd64.zip"
    sha256 "fe54e1feb72a1a771b2734358714059d302807ad0f33b84b6c5127f87c6f81c6"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/iann0036/iamlive/releases/download/v0.22.0/iamlive-v0.22.0-darwin-arm64.zip"
    sha256 "ef2989e177efbd44522c484628990e6291849f105e94727dfbaee562a762d440"
  end

  def install
    bin.install "iamlive"
  end
end
