# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Iamlive < Formula
  desc "Generate an IAM policy from AWS calls using client-side monitoring (CSM) or embedded proxy."
  homepage "https://github.com/iann0036/iamlive"
  version "0.0.46"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/iann0036/iamlive/releases/download/v0.0.46/iamlive-v0.0.46-darwin-amd64.zip"
    sha256 "da53a14e67299f20ec12fcc50866c19500442d4ca336b7dc03640a0fe5354d54"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/iann0036/iamlive/releases/download/v0.0.46/iamlive-v0.0.46-darwin-arm64.zip"
    sha256 "065b35d1560855b0e5e8f68515fdbcacbeaecc4a5192922cc04745a93780f746"
  end

  def install
    bin.install "iamlive-actiontesting"
  end
end
